site_name: VidarDB
theme:
    name: readthedocs
repo_url: https://github.com/vidardb/docs
site_author: VidarDB Team
copyright: 2020 VidarDB Inc. All Rights Reserved.
nav:
    - 'Welcome to VidarDB': 'index.md'
    - 'Run VidarDB in Docker': 'run_vidarDB_in_docker.md'
    - 'VidarDB Examples': 'example.md'
    - 'Run KMeans with VidarDB': 'run_kmeans_with_vidarDB.md'
    - 'Frequently Asked Questions': 'faq.md'
